#!/bin/sh 

# premium start/stop/restart script
# Michael Huber, TeliaCompany
# 2016-05-30 : First version

#SERVICE_WRITE_PID=1
#START=99
#STOP=20
#SERVICE_DAEMONIZE=1

# Binary
PREMIUMD=/usr/local/sbin/premiumd_daemon
FILE="/tmp/premiumd.log"

start() {
    
    # Verify that we are not already running, by checking that we have a logfile...   
    if [ -f $FILE ];
    then
        echo "Premiumd already started..."
        exit 0;
    fi
    
    touch $FILE

    # Start the daemon spawner...
    $PREMIUMD  $FILE &


    echo "Premiumd Startup OK"
    exit 1;
}

boot() {
        start "$@"
}


stop() {
    # Stop daemons.
    echo "Shutting down premiumd: "
    
    # Make sure it does not respawn...
    /bin/rm -f /tmp/premiumd.log
    
    # first send SIGTERM and give it a chance to terminate
    #kill -15 `cat /var/run/premiumd.pid`
    killall -15 premium
    sleep 3
    #kill -9 `cat /var/run/premium_daemon.pid`
    killall -9 premiumd_daemon
    echo 
}



# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    boot)
        start
        ;;
    restart|reload)
        stop
        sleep 3
        start
        ;;
    *)
        echo "Usage: /etc/init.d/premiumd {start|stop|restart}"
        exit 1
esac
